[features]
seeds = false
skip-lint = false

[programs.localnet]
signal_wars = "9s5gawgG2KJy7kofoxhRAve4zL6S7Y8dFuECtpbbBWJZ"

[programs.devnet]
signal_wars = "9s5gawgG2KJy7kofoxhRAve4zL6S7Y8dFuECtpbbBWJZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tests/tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[workspace]
members = ["programs/signal-wars"]
